### ISSUE TITLE
Can't use the level as ZIP-archive

### ISSUE THREAD

**Issue by Anton-V-K** [MrSimbax/colobot-alludo#10]
Installation instruction in README.md is confusing:

> Download the latest release from here and put it in <colobot_data_directory>/mods folder (unpacking is not necessary).

ZIP-ed archive (like `colobot-alludo-1.4.1.zip`) isn't picked up by Colobot 0.1.11 (Windows 7 64-bit) when placed in `/mods` or `/mods/alludo`.
Removing extra dir (like `colobot-alludo-1.4.1`) inside the ZIP-archive and placing the restructured archive under `/mods/alludo` doesn't work either.
I guess, ZIP-ed mods are no longer supported/working...

**Comment by krzys-h** [comment]
Huh, that's really strange... I'll check that later. It really should work.
Are you sure you're putting the file in mods directory in the data dir? (`C:\Program Files\Colobot\data\mods`, not `C:\Program Files\Colobot\mods`) You can also try the user mods directory (`C:\Users\username\colobot\mods`)
The .zip file should be without the extra directory. Unfortunately GitHub adds that automatically when you use the 'source code' download, and it looks like @MrSimbax didn't upload additional .zip files in the proper format when releasing new versions.

**Comment by Anton-V-K** [comment]
Yes, the directories are correct - I've placed unzipped content there, and it works fine.
I made another attempt and the ZIPed content seems to be loaded fine when there is no extra directory inside the archive (so it should be re-packed). And the ZIP-file should be placed directly under `mod` folder (both global, and user locations work fine).
The issue may be closed as soon as ZIP-file is re-released and/or the instruction is adjusted.

**Comment by MrSimbax** [comment]
This means that there would need to be two .zips with almost the same content:

1. one for using the .zip without unpacking (without the root directory)
2. one which should be unpacked (with the root directory, automatically generated by GitHub).

I don't agree with that solution at all.

1. It is good practice to have the extra directory in a .zip file, because you can unzip the content directly without worrying that the files from the archive will mix with other files in the destination folder. Without the extra directory, you have to create the destination directory manually.
2. It will create unnecessary confusion for end users since both .zip files will have the same content, with or without the extra directory.
3. Each release would have to be packaged manually, just to get rid off the root directory.

The second solution sucks too. It's either removing the note that "unpacking is unnecessary" completely or telling the users to first unpack the archive, pack the files inside the root directory into a new archive, and then copying that to mods. That is something I would not call convenient.

I think that Colobot should be able to load both versions of the .zip, with the extra directory or not. If it doesn't, then this feature seems to create just more confusion than convenience. And convenience is the whole point of this feature, isn't it?

**Comment by krzys-h** [comment]
I agree that this is not really a clean solution, but it's how we've always done it. In the future, the source code may be different from the built level, e.g. if we add some scripts for generating the museum of objects. And supporting both types of archives in Colobot would mean that if you create a mod that has only one directory (e.g. only "levels"), it would be automatically skipped, creating even more confusion. And i'm not sure it's even possible to mount subdirectory of an archive in physfs.

**Comment by MrSimbax** [comment]
I'd rather have modders a little confused than the end users, but I get your point. Very well, I'll prepare the releases.
